### ISSUE TITLE
dau need help

### ISSUE THREAD

**Issue by Dalbyte** [frank-dspeed/esnext-cctalk#2]
Hello, I am trying to install an EMP 830.14 v5 USB in my first Electron application.

Spent a whole week getting my setup running, but nothing seems to work.

My attempts:
1 - npm ccTalk from Lucas Winter but that didn't work with my nodejs version. I don't understand why.

2 - npm serialport and then tried to send a simple accepted 0 command and a simplePoll 254 to the port.
I also tried a port.pipe as stated in the documentation, but I got no response.

3 - Then I stumbled across your projects on ccTalk. But I didn't got any further.

4 - I had never tested the coin validator and stumbled upon a working #C project from 2005.
https://wiki.hamburg.ccc.de/Muenzpruefer
And the coin validator worked.

5 - I installed Rust and Typcript for your project.
npm installation now works without errors.

My goal is to detect if someone has thrown a coin into the slot.

I am thankful for every help.
:)

**Comment by frank-dspeed** [comment]
@Dalbyte I am at present refactoring this project a lot and test it with all kind of devices.

That sayed: CCTalk handling in production is not a easy task and often needs customizing the read loop.

but for your case i can prepare a example for you under /examples/node-serialport/emp800-only.js

It will take some time till the event parser works with all devices i am doing a generic one at present

so the example will simply emit [ eventCount, [...fiveChannelEventPairs]].

you need to parse that result then yourself into usefull data depending on your device configuration.

if your not familar with raw CCTalk usage you will not get happy with the nodejs implementation till it is more complet.

**Comment by frank-dspeed** [comment]
Oh and Sorry for the rust dependency it is currently only inside for verification and developer tests i need to exclude it from the general project..

It is not really needed i got a crc16xmodemJs implementation and it looks working i only tought it is not working but it was not the failure of the imolementation.

**Comment by Dalbyte** [comment]
@frank-dspeed Thank you for prepare a example. If you need any vector illustration for the project, feel free to write me.

**Comment by frank-dspeed** [comment]
@Dalbyte https://github.com/frank-dspeed/esnext-cctalk/blob/main/examples/nodejs-serialport/emp800-only.js
